### ISSUE TITLE
Applicability to other RL78 chips? 

### ISSUE THREAD

**Issue by DragRedSim** [AbkarinoMHM/PS4SysconTools#9]
I came across this project in my research regarding the RL78/G14 chip, which was used for LED light control on a PC motherboard that I own (MSI X470 Gaming M7 AC). Unfortunately, the manufacturer has had a bad habit of releasing firmware updates that would brick this functionality. I was wondering if the information and tools here could be utilised on the G14-series chips, as this might produce a way to unbrick the lighting that this board is supposed to offer (if a suitable donor dump can be created from a working board; my theory is that the firmware update tool is writing the update to the wrong section of the chip, clobbering the preinstalled bootloader, based on the firmware file provided not appearing to include a header table.)

**Comment by AbkarinoMHM** [comment]
Hello,
I'm so sorry for the late reply, actually out tool utilize an exploit that exist in Renesas RL78/G13 ROM v3.03 specially, so i'm not sure if such exploit is exist also on G14 or not.
Also this exploit used to enable debug mode so we can upload payload in RAM and run it since the PS4 Syscon was locked and debug mode was disabled.
